### PR TITLE
Requirements fix for adal version.

### PR DESCRIPTION
**Pull request by bulkware**

### CODE REVIEW

**Review by sapajune — APPROVED** [review]
Could've also checked if other dependencies could be changed. Note that all other required packages specify only two numbers so they'll use x.y.0 -version and won't get any bugfixes and as such their dependencies might break unexpectedly.

**Comment by sapajune** [comment]
Checked the listed azure libs in PyPi and current fixed versions are ok and don't have matching patch releases although getting quite old (which means they might fall out of support).

If planning to update versions should check breaking changes lists for each lib.

**Comment by bulkware** [comment]
Actually, I just now made a clean, new virtualenv and installed zabbix-azure-monitoring with this change and it resulted in PyJWT version 2.3.0 in which the error occurs. So I allowed other libraries to install versions defined using ~= syntax and the same happened. What now?

**Comment by sapajune** [comment]
Does cause an issue? adal 1.2.7 explicitly allows use of PyJWT 2.x so I would assume it should work with it.

See here: https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.2.7/setup.py

**Comment by sapajune** [comment]
The 1.2.7 code addresses differences between PyJWT versions: https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/e5f662f26b81f23a19e6caeab7f19f578d1306d1/adal/self_signed_jwt.py#L59

**Comment by bulkware** [comment]
> Does cause an issue? adal 1.2.7 explicitly allows use of PyJWT 2.x so I would assume it should work with it.
> 
> See here: https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.2.7/setup.py

Yup, it throws the same error we encountered yesterday.

**Comment by sapajune** [comment]
> > Does cause an issue? adal 1.2.7 explicitly allows use of PyJWT 2.x so I would assume it should work with it.
> > See here: https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.2.7/setup.py
> 
> Yup, it throws the same error we encountered yesterday.

Seems strange since the code I linked clearly addresses the issue. What version of adal it installs?

**Comment by sapajune** [comment]
I think I found the problem. Note that versions that are used when installing module are defined in setup.py, not by requirements.txt.

**Review by sapajune — CHANGES_REQUESTED** [review]
Fix setup.py. I suggest not fixing PyJWT version at all in either file since packages usually know their dependency requirements better than their users. 😄

**Comment by bulkware** [comment]
> Fix setup.py. I suggest not fixing PyJWT version at all in either file since packages usually know their dependency requirements better than their users. 😄

In commit 3090a95bb30808002bbac6867066bbdec3ad57c8. I can't believe I forgot "setup.py". Now it works, thank you :)

**Review by sapajune — APPROVED** [review]

**Pull request merged**
